# Generated by Django 5.2 on 2025-05-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_album_photo_albumphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumphoto',
            old_name='photo',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gallery.album'),
        ),
    ]
