# Generated by Django 5.2 on 2025-05-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_aboutme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type_of_content',
            field=models.CharField(choices=[('video', 'Відео'), ('photo', 'Фото')], default='photo'),
        ),
    ]
