# Generated by Django 5.2 on 2025-05-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_category_type_of_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphoto',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='album/'),
        ),
    ]
