# Generated by Django 5.2 on 2025-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_albumphoto_link_alter_albumphoto_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumphoto',
            name='link',
        ),
        migrations.AlterField(
            model_name='category',
            name='type_of_content',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Відео')], default='photo'),
        ),
    ]
