# Generated by Django 5.2 on 2025-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_remove_albumphoto_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphoto',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
