# Generated by Django 5.2 on 2025-05-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_albumphoto_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumphoto',
            old_name='category',
            new_name='album',
        ),
    ]
