# Generated by Django 5.2 on 2025-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_album_slug_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_of_content',
            field=models.CharField(choices=[('video', 'Відео'), ('photo', 'Фото')], default='photo'),
        ),
    ]
