# Generated by Django 5.2 on 2025-05-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_alter_album_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
