# Generated by Django 5.2 on 2025-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_alter_category_type_of_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_of_content',
            field=models.CharField(choices=[('video', 'Відео'), ('photo', 'Фото')], default='photo'),
        ),
    ]
