# Generated by Django 5.2 on 2025-05-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_alter_category_type_of_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='banner_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_of_content',
            field=models.CharField(choices=[('video', 'Відео'), ('photo', 'Фото')], default='photo'),
        ),
    ]
